---
title: "Week 7"
author: "Cole Jower"
date: "October 4, 2017"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r test1}
test1 = "The current year is 2016"

my_pattern = "[xqb]"
my_pattern = "[0-9]"
grepl(pattern = my_pattern, test1)

temp = gregexpr(my_pattern, test1)
string_position = temp[[1]]

gregexpr("[[:blank:]]", test1)


test1 = "The current year is 2016"
grepl(pattern = "[[:upper:][:digit:]]", test1)

temp = regexpr(pattern = "[[:blank:]]", test1)
firstspace = temp[[1]][1]

my_pattern = "[[:lower:]].[[:digit:]]"
grepl(my_pattern, test1)


loc = gregexpr(my_pattern, test1)[[1]][1]

temp = gregexpr(my_pattern, test1)[[1]][1]
loc = temp[[1]][1]

my_pattern = "\\s[[:lower:]][[:lower:]]\\s"
gregexpr(my_pattern, test1)
loc = gregexpr(my_pattern, test1)[[1]][1]

text2 = sub(my_pattern, replacement = " is not ", test1)

my_pattern = "\\s[[:lower:]]{2}\\s"
gregexpr(my_pattern, test1)[[1]][1]
                                
my_pattern = "\\d{4}"
temp = gregexpr(my_pattern, text2)
string_pos4 = temp[[1]][1]

# Ex 10
substr(text2, start = string_pos4[[1]][1], stop = string_pos4+1)



string_pos4 = substr(text2, start = temp[[1]][1], stop = nchar(text2))

```
